# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
    ]
